"""Content for the Navy Deployment Packing List pages.

Source: SAVIOR_SAILOR_EBOOK.pdf ("20+ Essentials for Deployment") by Alex Velichko.
Each item keeps Alex's original ebook blurb verbatim in `alex` (empty when the
ebook had none) and adds one or two sentences of web copy in `why`.
`asin` is the Amazon product from the ebook; `search` is used for the few items
that only had an Amazon search link.

Regenerate the pages with:  python3 scripts/build_packing_list.py
"""

AFFILIATE_TAG = "saviorsailor-20"

HUB = {
    "slug": "deployment-packing-list",
    "title": "Navy Deployment Packing List: 20+ Essentials",
    "meta_title": "Navy Deployment Packing List: 20+ Essentials | Savior Sailor",
    "description": "What to pack for a Navy deployment, from a sailor with 22 months at sea. 150+ essentials for your rack, the gym, the head and liberty, organized by category.",
    "intro": [
        "Hello! I am so glad we have found each other. My name is Alex, but I used to go by FCA2(SW) Velichko. Over 8 years of service in the United States Navy and more than 22 months collectively at sea, I always seemed to be missing something. This is why I founded Savior Sailor and created this resource.",
        "I personally made a list and then interviewed 30+ service members, and with some time the Savior Sailor ebook was the outcome. Here it is as a set of web pages so you can read it on your phone, share a chapter with a family member, or check things off while you shop. Whether it is your first or last time leaving home, Savior Sailor is here for you.",
    ],
}

CHAPTERS = [
    {
        "slug": "comfort",
        "label": "Comfort",
        "title": "Comfort Items for Navy Deployment",
        "meta_title": "Comfort Items for Navy Deployment | Packing List",
        "description": "Hammocks, camping chairs, coveralls and other comfort items that make months at sea easier. Chapter 1 of the Savior Sailor deployment packing list.",
        "intro": "Ships are built for the mission, not for you. The few comfort items you bring are the difference between counting the days and actually settling in. These are the ones I never deployed without.",
        "items": [
            {"name": "Hammock", "asin": "B0B785WHZP",
             "alex": "Talk to your work center supervisor prior to make sure you have somewhere to hang it up. Only to be used after hours and must be stowed away during the day.",
             "why": "A rack is not the only place to sleep. On a long transit, an after-hours hammock in the shop is the best nap you will get on the ship."},
            {"name": "Camping Chair", "asin": "B09TDGG6KH",
             "alex": "This is honestly more of a necessity than “Luxury.”",
             "why": "There are never enough places to sit outside of the mess decks. A folding chair that packs flat gives you a seat on the fantail, in the hangar bay or wherever you get a few minutes off your feet."},
            {"name": "Floor Camping Mat", "asin": "B0BLNKR14R",
             "alex": "To save your back during your cat naps on the ground.",
             "why": "Nonskid decks are brutal on your back. A rolled-up sleeping pad turns any corner of the work center into a place you can actually rest during a long evolution."},
            {"name": "Neck Pillow", "asin": "B07SRRQS5B",
             "alex": "Small/portable and great for when you are laying on the floor or your chair/hammock. PLUS you can use it for your flights back home on leave.",
             "why": "It weighs nothing, clips to your bag and turns a chair or a mat into a place you can sleep. It also earns its keep on the flight home."},
            {"name": "Clip Fan", "asin": "B089Q8LQZ5",
             "alex": "Berthing can get very hot in the summer.",
             "why": "Berthing ventilation goes down more often than anyone admits, and the Gulf in August is no joke. A small rechargeable clip fan on your rack rail is the cheapest good night's sleep you will buy."},
            {"name": "Bulwark or Carhartt Coveralls", "asin": "B0078R4S9C",
             "alex": "Much more comfortable than ship issued coveralls. Once you wear these you will not go back!",
             "why": "You live in coveralls underway, so the fit and fabric matter more than anything else you wear. Check your command's uniform policy first, since some ships only allow the issued ones."},
            {"name": "Slip-On Boots", "asin": "B09HWQ8PMG",
             "alex": "All the cool kids have them! These are great for when you are in a hurry.",
             "why": "When general quarters or a flight quarters call goes out at 0200, laces cost you time. Slip-ons get you out of the rack and moving in seconds."},
            {"name": "Watch", "asin": "B000GAYQL8",
             "alex": "If you don’t have one already, are you really even in the military?",
             "why": "Phones get secured in certain areas and die at the worst times. A tough, water-resistant watch with a backlight is what you actually read at 0345 for watch relief."},
            {"name": "Vacuum Seal Bags", "asin": "B0973DGD8P",
             "alex": "As stated before you have limited space so these are handy for civilian attire or a big jacket you may bring with you.",
             "why": "Your entire life fits in a coffin locker and a stand-up locker. Compressing civilian clothes and a jacket down to a quarter of the size gives you room for everything else on this list."},
            {"name": "Desk Organizer", "asin": "B09K5927B5",
             "alex": "The work center will love you!",
             "why": "Shared desks in the shop turn into a pile of tags, pens and chits within a week. A small organizer keeps your logs and paperwork where you can find them."},
            {"name": "Wrench Set", "asin": "B0CHYK75D4",
             "alex": "Just when you need something, someone else is using it! Avoid this problem with your own small set of tools that you use the most!",
             "why": "Tool issue takes time and the set you need is always signed out. A compact personal set covers the small jobs, but follow your command's tool control rules and keep it out of maintenance you are not authorized for."},
            {"name": "Sunglasses", "asin": "B076DX99QJ",
             "alex": "",
             "why": "Sun off the water is twice as bright as sun on land, and you will spend hours topside for sea and anchor detail, flight ops and working parties. A quality pair is protection, not style."},
        ],
    },
    {
        "slug": "entertainment",
        "label": "Entertainment",
        "title": "Entertainment Essentials for Deployment",
        "meta_title": "Entertainment Essentials for Navy Deployment | Packing List",
        "description": "Headphones, chargers, a Kindle, games and everything else that keeps you sane on a long deployment. Chapter 2 of the Savior Sailor deployment packing list.",
        "intro": "Free time underway is short and unpredictable, and Wi-Fi is either slow or gone entirely. Bring your entertainment with you, plan for Bluetooth to be secured, and make sure you can keep it all charged from one outlet.",
        "groups": [
            {"heading": "Electronics", "items": [
                {"name": "Wired Earbuds", "asin": "B07SJ8Z9YL",
                 "alex": "The ship will secure Bluetooth while operating in certain areas of the world. You need to have wired headphones so you can still listen to music.",
                 "why": "When emissions control goes into effect your wireless gear is useless, sometimes for weeks. A cheap wired pair is the backup that keeps your music and movies going."},
                {"name": "Bluetooth Speaker", "asin": "B08NLCW9WY",
                 "alex": "Great for your workspace or during the daily “Clampdown”.",
                 "why": "Cleaning stations go faster with music, and a good speaker makes you the most popular person in the shop. Get one that can take a drop on a steel deck."},
                {"name": "Auxiliary Cord or Phone Adapter", "asin": "B0CGDFGKYY",
                 "alex": "When Bluetooth is secured this will enable you to still be able to use your speaker with an auxiliary cord.",
                 "why": "Most phones no longer have a headphone jack, so the adapter is what connects your phone to the speaker and the earbuds above. Buy two, because they get lost."},
                {"name": "Portable Charger", "asin": "B01JIWQPMW",
                 "alex": "While on liberty, the last thing you need is a dead phone. Stay charged up with this!",
                 "why": "On a port call your phone is your map, your translator and your way back to the ship before liberty expires. A power bank also covers you during a long watch or when berthing power is secured."},
                {"name": "Bluetooth Headphones", "asin": "B0CCZ26B5V",
                 "alex": "When Bluetooth is not secured you can enjoy these.",
                 "why": "Berthing is 100 people, one passageway and zero privacy. Noise-cancelling headphones are how you get a movie, a nap or a phone call to yourself."},
                {"name": "Charger Block with Multiple USB Ports", "asin": "B0BDLLJBDQ",
                 "alex": "Your rack only has one outlet so having this will enable you to charge more than one device.",
                 "why": "One outlet has to cover your phone, headphones, watch, speaker and fan. A multi-port block solves that without the power strip your ship's electrical safety rules will not allow."},
                {"name": "Pop Socket or Socket Holder", "asin": "B01EFPKMH6",
                 "alex": "Gives you an in hand luxury feel with your phone. The socket holder is great to stick in your rack so you can “mount” your phone to watch movies.",
                 "why": "Stick the holder on the rack above your head and your phone becomes a screen you do not have to hold. It is the cheapest rack upgrade in this whole list."},
                {"name": "Laptop", "asin": "B0C3FBFCNG",
                 "alex": "Having a computer is great if you want to watch movies or play computer games in your free time.",
                 "why": "It does not need to be a gaming rig, but a laptop you own means movies, college courses and games that do not depend on the ship's network. Load it up before you leave the pier."},
                {"name": "Portable Hard Drive (SSD)", "asin": "B08QBMD6P4",
                 "alex": "Store anything you want on this. Most common is to put movies/shows on here. Trade with your shipmates and build your collection!",
                 "why": "Streaming does not exist underway, so the drive full of shows is your library for the next seven months. Solid state drives shrug off the vibration and knocks that kill spinning disks."},
                {"name": "Kindle", "asin": "B09TMN58KL",
                 "alex": "With limited storage space this allows you to have as many books as you want!",
                 "why": "Paperbacks take up locker space and fall apart in the humidity. A Kindle holds a whole deployment of reading, and the battery lasts weeks between charges."},
                {"name": "Game Console", "asin": "B0BFJWCYTL",
                 "alex": "Don’t forget to buy extra games so you don’t get bored!",
                 "why": "A handheld console fits in your rack and gives you something to do that is not scrolling through the same downloaded photos. Local multiplayer with shipmates is where the real hours go."},
            ]},
            {"heading": "Messdeck Fun", "items": [
                {"name": "Playing Cards", "asin": "B0021JL0ZM",
                 "alex": "",
                 "why": "Spades on the mess decks is a Navy tradition for a reason. A deck of cards fits in a coverall pocket and never needs charging."},
                {"name": "Uno", "asin": "B07TJT135V",
                 "alex": "",
                 "why": "Everyone knows the rules, a round takes ten minutes and it gets loud. Perfect for the gap between chow and your next watch."},
                {"name": "What Do You Meme?", "asin": "B01MRG7T0D",
                 "alex": "",
                 "why": "Long deployments run on inside jokes. A party game like this one is how a new work center turns into a crew."},
                {"name": "Jenga", "asin": "B00ABA0ZOA",
                 "alex": "",
                 "why": "Jenga on a moving ship is a completely different game. Bring it for the laughs alone."},
                {"name": "Fidget Spinner", "asin": "B071KZS7H1",
                 "alex": "",
                 "why": "Standing a four-hour watch with nothing to do with your hands is harder than it sounds. Something small and quiet to fidget with helps the time pass."},
            ]},
        ],
    },
    {
        "slug": "rack-hacks",
        "label": "Rack Hacks",
        "title": "Rack Hacks: How to Sleep Better on a Navy Ship",
        "meta_title": "Rack Hacks: Sleep Better on a Navy Ship | Packing List",
        "description": "Rack pads, sleep masks, ear plugs, rack lights and the small items that turn a Navy rack into a place you can actually sleep. Chapter 3 of the deployment packing list.",
        "intro": "Your rack is about six feet long, two feet wide and the only space on the ship that is yours. Set it up right on day one and it becomes the one place you can shut the door on the rest of the deployment.",
        "items": [
            {"name": "Rack Pad", "asin": "B01N41IPPI",
             "alex": "",
             "why": "The issued mattress is a thin foam pad on a steel tray. A twin memory foam topper, trimmed to fit, is the single biggest upgrade you can make to your sleep underway."},
            {"name": "Extra Black Socks", "asin": "B00UBEGA40",
             "alex": "",
             "why": "Laundry day comes once a week if you are lucky, and socks disappear in the ship's laundry. Bring more than you think you need and rotate them so your boots stay dry."},
            {"name": "Extra Tan T-Shirts", "asin": "B071WCTV7Y",
             "alex": "",
             "why": "You will sweat through a shirt a day in the engine room or on the flight deck. Extras mean you are not wearing yesterday's shirt because laundry is backed up."},
            {"name": "Beanie Cap", "asin": "B01LXCBA22",
             "alex": "",
             "why": "Berthing air conditioning has two settings: broken and freezing. A beanie is also the fastest way to get warm on a night watch topside, where authorized."},
            {"name": "Extra Pillowcase", "asin": "B09BFPB3NZ",
             "alex": "The ship will issue one to you but having a spare is nice to keep your pillow fresh.",
             "why": "One pillowcase and a weekly laundry cycle is a bad combination. Swap the spare in mid-week and your rack smells like a bed instead of a berthing compartment."},
            {"name": "Blanket or Sleeping Bag", "asin": "B077XQDZW4",
             "alex": "Do you really want to sleep with a wool blanket???",
             "why": "The issued wool blanket is scratchy and does not wash well. A lightweight sleeping bag packs small, unzips into a blanket and feels like something from home."},
            {"name": "Ear Plugs", "asin": "B08MFDT65P",
             "alex": "For uninterrupted sleep.",
             "why": "Berthing never goes fully quiet: watch reliefs, the 1MC, the guy above you snoring and the ship itself. Reusable ear plugs are the difference between six hours of sleep and three."},
            {"name": "Sleep Mask", "asin": "B07KC5DWCC",
             "alex": "Great for sleeping in the top rack because you have no overhead covering to block out light.",
             "why": "Half the compartment is on a different watch rotation than you, so the lights are never all off. A contoured mask blocks it out without pressing on your eyes."},
            {"name": "Disinfectant Wipes", "asin": "B0082CX1UY",
             "alex": "Kill those germs! Give your rack a good wipe before moving in to start clean and fresh!",
             "why": "Someone slept in that rack before you. Wipe down the tray, the rails, the light and the locker before you unpack, and keep the tub for the inevitable crud that goes around the ship."},
            {"name": "Phone Clamp", "asin": "B07S9JXQP2",
             "alex": "Great for holding your phone/tablet to watch movies in your rack. 3M Velcro tape works great also!",
             "why": "A gooseneck clamp on the rack rail puts the screen right where you want it, hands free. It is the rack theater setup every sailor ends up copying."},
            {"name": "Rack Light", "asin": "B0C9CSVSNY",
             "alex": "Berthing is often dark which makes grabbing things a challenge. Don’t turn the aisle light on, grab one of these and your rack mates will thank you.",
             "why": "A magnetic, rechargeable light sticks to the rack frame and gives you enough to read, get dressed or find your boots without waking the compartment. Get one with a red mode for the darkened-ship hours."},
            {"name": "Combination Locks", "asin": "B00004SQLJ",
             "alex": "Combination lock removes the need to carry a key. WRITE THE CODE DOWN",
             "why": "You need one for your bunk locker and one for each foot locker, so buy a set that shares a combination. Keys get lost at sea and a locksmith is a long way away."},
            {"name": "Clothesline Rope", "asin": "B09FPQRWFL",
             "alex": "Great for hanging wet towels.",
             "why": "Towels do not dry folded in a locker, they mildew. A few feet of paracord strung in your rack or the shop gives everything a place to dry."},
            {"name": "Thermals (Men's)", "asin": "B019EEJX8M",
             "alex": "Depending on where you are located or what time of the year it is, thermals will help you contain your body heat to keep you warm in the cold weather.",
             "why": "A winter North Atlantic or Pacific transit is cold in a way coveralls alone do not handle. Fleece-lined thermals under your uniform make a topside watch survivable."},
            {"name": "Thermals (Women's)", "asin": "B019X2NGII",
             "alex": "Depending on where you are located or what time of the year it is, thermals will help you contain your body heat to keep you warm in the cold weather.",
             "why": "Same idea, cut to fit. Get a set that wicks sweat as well as it insulates, because you will go from a cold weather deck to a hot space in a single trip."},
        ],
    },
    {
        "slug": "health-fitness",
        "label": "Health & Fitness",
        "title": "Health and Fitness Gear for Deployment",
        "meta_title": "Health & Fitness Gear for Navy Deployment | Packing List",
        "description": "Filtered water bottles, shaker bottles, protein, pre-workout and a jump rope: the gym gear worth bringing on a Navy deployment. Chapter 4 of the packing list.",
        "intro": "The ship's gym is small, crowded and usually open when you are working. The people who come home in better shape than they left are the ones who made it easy on themselves: their own bottle, their own supplements and a workout they can do anywhere.",
        "items": [
            {"name": "Filtered Water Bottle (Brita)", "asin": "B08FSBZK82",
             "alex": "The ship water has added chemicals to help purify but this causes the water to taste different. Brita filtered water bottle will help with this.",
             "why": "Ship water is safe, but the bromine taste puts a lot of sailors off drinking enough of it. A filtered bottle fixes the taste, and you will drink more water because of it."},
            {"name": "Shaker Bottle", "asin": "B01LZQ8OYE",
             "alex": "For your protein/pre workout. If you already have one – get a back up!",
             "why": "Shaker bottles crack, get left in the gym and go missing from the shop fridge. A spare costs a few dollars and saves you from stirring protein with a fork."},
            {"name": "Bottle Brush", "asin": "B087PC9KCD",
             "alex": "If you use a shaker bottle you probably know about “the smell”. A brush will help fight this.",
             "why": "There is no dishwasher for your personal gear. A long brush and the dish soap from the food chapter are how the shaker bottle survives seven months."},
            {"name": "Protein Powder", "asin": "B000GISTZ4",
             "alex": "To grow big and strong.",
             "why": "The galley menu is not built around your macros. A tub of protein fills the gap on the days the chow line is carbs and mystery meat, and the ship's store rarely stocks it."},
            {"name": "Pre-Workout", "asin": "B07F3ZSWZ7",
             "alex": "When you need that extra boost to get you in the gym after working all day.",
             "why": "After a twelve-hour day the gym is a hard sell. Check the ingredients against your command's supplement policy before you pack it."},
            {"name": "BCAAs", "asin": "B07BV6Y72J",
             "alex": "This will help your muscles recover.",
             "why": "Recovery is slower when you are sleeping five hours a night on a moving ship. A flavored amino drink also makes plain ship water easier to get down."},
            {"name": "Insulated Bottle (Yeti)", "asin": "B07FM5HLMF",
             "alex": "For hot/cold drinks.",
             "why": "Coffee goes cold in minutes on a windy weather deck and water goes warm in a hot space in about the same time. A steel insulated bottle keeps both where you want them through a full watch."},
            {"name": "Jump Rope", "asin": "B09DF9NWC7",
             "alex": "Great for a cardio alternative when the treadmill or bike/row machine gets old.",
             "why": "There are three treadmills for a crew of hundreds. A jump rope in a corner of the hangar bay is cardio with no waiting list."},
        ],
    },
    {
        "slug": "food-drinks",
        "label": "Food & Drinks",
        "title": "Snacks and Drinks to Pack for Deployment",
        "meta_title": "Snacks & Drinks to Pack for Navy Deployment | Packing List",
        "description": "The snacks, drink mixes, coffee gear and mess kit worth bringing on a Navy deployment, plus why each one matters underway. Chapter 5 of the packing list.",
        "intro": "The galley feeds you, but it feeds you on its schedule, and the ship's store sells out of the good stuff in the first two weeks. This is the list of what to stock in your locker. These are some ideas to get you started, but make sure you buy your favorites.",
        "groups": [
            {"heading": "Snacks and Drink Mixes", "items": [
                {"name": "Powdered Drink Mixes (Mio, Crystal Light)", "asin": "B09MSTYYPM",
                 "alex": "",
                 "why": "Ship water tastes like ship water. A drink mix makes every canteen fill something you actually want, and the caffeinated ones are cheaper than the energy drinks in the ship's store."},
                {"name": "Candy", "asin": "B0CFYXNYMC",
                 "alex": "",
                 "why": "A bag of candy in your locker is currency, morale and a mid-watch pick-me-up all in one. Buy the individually wrapped kind so it survives the heat."},
                {"name": "Gum", "asin": "B001NI0MQ0",
                 "alex": "",
                 "why": "Long watches, meetings and long stretches between chances to brush your teeth. Gum covers all three."},
                {"name": "Beef Jerky", "asin": "B014ABUQVC",
                 "alex": "",
                 "why": "Real protein that needs no fridge and no prep. It is what you eat when you missed chow because of an evolution and the next meal is five hours away."},
                {"name": "Snack Box", "asin": "B01N22CM3F",
                 "alex": "",
                 "why": "A variety box is the easy way to stock a locker without deciding on forty things. It is also the most-requested item in the care packages we send."},
                {"name": "Instant Coffee", "asin": "B00E36ZFNE",
                 "alex": "",
                 "why": "Galley coffee has been on the burner since the last watch. Single-serve instant packets and hot water from any coffee mess get you a cup that does not taste burnt."},
                {"name": "Assorted Tea Bags", "asin": "B075F9Y19M",
                 "alex": "",
                 "why": "Not everyone runs on coffee, and hot water is available around the clock. A tea sampler covers the night watch, a sore throat and winding down before you hit the rack."},
                {"name": "Creamer", "asin": "B0CGB3JR7L",
                 "alex": "",
                 "why": "Fresh milk is gone a couple of weeks out of port. Single-serve creamers keep your coffee drinkable for the rest of the deployment."},
                {"name": "Slim Jims", "asin": "B0D1BR7ZWS",
                 "alex": "",
                 "why": "They fit in a coverall pocket, last forever and taste like home. A box of them will make you friends in the shop."},
                {"name": "Mixed Nuts", "asin": "B00CPS6VTO",
                 "alex": "",
                 "why": "Dense calories and protein for the stretches when you are working through a meal. Single-serve bags keep them fresh in a humid locker."},
                {"name": "Seeds", "asin": "B0B35B46WJ",
                 "alex": "",
                 "why": "Sunflower seeds are the unofficial snack of every lookout and bridge watch. They keep you awake and give your hands something to do at 0300."},
                {"name": "Snack Bars", "asin": "B08SPDZ226",
                 "alex": "",
                 "why": "Breakfast in the morning rush is often a bar eaten on the way to quarters. Keep a box in your locker and one in your pocket."},
                {"name": "Chips", "asin": "B09J1NN28Q",
                 "alex": "",
                 "why": "The ship's store runs out of chips first, every time. A variety pack in your locker makes you the person everyone comes to on week three."},
                {"name": "Popcorn", "asin": "B00I9VCF0U",
                 "alex": "",
                 "why": "Most work centers and lounges have a microwave. Popcorn plus the movie drive from the entertainment chapter is a rack night done right."},
                {"name": "Cereal", "asin": "B07PS3546D",
                 "alex": "",
                 "why": "Single-serve cereal cups mean breakfast even when you cannot make it to the galley. They also make a fine dry snack when the milk is long gone."},
                {"name": "Ramen", "asin": "B0B2PHBL87",
                 "alex": "",
                 "why": "Hot water is everywhere on a ship, so ramen is the original mid-rats. Bring the good kind; you will be eating a lot of it."},
                {"name": "Instant Rice", "asin": "B08ZKQTSBP",
                 "alex": "",
                 "why": "A microwaveable rice cup is a real meal in ninety seconds. Combine it with the spices below and your locker starts to outperform the galley."},
                {"name": "Mac and Cheese Cups", "asin": "B00WI0T4HU",
                 "alex": "",
                 "why": "Just add water, microwave, done. It is comfort food for the nights the menu lets you down."},
                {"name": "Kodiak Flapjack Power Cups", "asin": "B09RQ1SRTQ",
                 "alex": "",
                 "why": "Protein pancakes from a cup and hot water. They fill the gap between the gym and a galley breakfast you already missed."},
                {"name": "Takis", "asin": "B087JJCJVX",
                 "alex": "",
                 "why": "Every ship has a Takis economy. Whether you eat them or trade them, they are worth locker space."},
                {"name": "Applesauce Pouches", "asin": "B001VJ70UC",
                 "alex": "",
                 "why": "Fresh fruit disappears a few weeks into deployment. Pouches are the fruit you can still get on week ten, and they need no fridge."},
                {"name": "Fruit Roll-Ups and Gushers", "asin": "B07RTJWCMS",
                 "alex": "",
                 "why": "Pure nostalgia. On a bad day a Gusher from the bottom of your locker does more for morale than it should."},
                {"name": "Protein Bars", "asin": "B07J2MM23Z",
                 "alex": "",
                 "why": "The most reliable meal replacement on the ship. Keep a few in the pocket of your coveralls for the days the evolution runs straight through chow."},
            ]},
            {"heading": "Coffee and Mess Gear", "items": [
                {"name": "AeroPress", "search": "AeroPress coffee maker",
                 "alex": "More compact than a French press AND makes a smoother Cup of Joe!",
                 "why": "Real coffee underway is a luxury very few people have. The AeroPress is plastic, nearly unbreakable and makes a better cup than anything on the ship."},
                {"name": "Spices and Sauces", "asin": "B0BS82JCS3",
                 "alex": "Taco Tuesday and they ran out of hot sauce?!? Good thing you have your own. Burger Wednesday and there is no more ketchup?!? WELL…..good thing you have your own. You get the point haha make sure to get spices that you use regularly as well.",
                 "why": "Galley food is cooked for hundreds and seasoned for none of them. A small kit of your own spices and a bottle of hot sauce fixes almost any meal."},
                {"name": "Reusable K-Cup", "asin": "B09WRD66FL",
                 "alex": "Some work centers will have a Keurig. Make sure you have one of these so you can make your own coffee.",
                 "why": "K-Cups run out, ground coffee does not. A reusable pod lets you bring a bag of the coffee you actually like and use the shop's machine all deployment."},
                {"name": "Spork", "asin": "B015MM5OEM",
                 "alex": "If they lock the scullery up at night because people aren’t returning silverware you will be glad you have this for your snack before that night watch!",
                 "why": "A steel camping spork lives in your pocket or your rack and means you never eat mac and cheese with your hands. Mid-rats do not come with utensils."},
                {"name": "Food Containers", "asin": "B07G92P81W",
                 "alex": "Use this to save food on nights you really enjoyed the meal and eat it the next day when the food is not as good. Or if you are bulking and need more calories.",
                 "why": "Leakproof containers that nest are the ones that survive a locker. They also keep opened snacks away from the humidity and whatever else lives in berthing."},
                {"name": "Dish Soap", "asin": "B07Q6PH3NK",
                 "alex": "To wash out your Tupperware or shaker bottle.",
                 "why": "Ship sinks come with hand soap, not dish soap. A small bottle keeps your bottle, spork and containers from developing the smell that gets them thrown out."},
            ]},
        ],
    },
    {
        "slug": "hygiene",
        "label": "Hygiene",
        "title": "Hygiene and Toiletries Checklist for Deployment",
        "meta_title": "Hygiene & Toiletries Checklist for Navy Deployment | Packing List",
        "description": "The full toiletries, grooming, shower and laundry checklist for a Navy deployment, so you do not forget anything before you leave the pier. Chapter 6 of the packing list.",
        "intro": "Everyone has their own preferred brand and scent, so treat this as a check-off list rather than a shopping list. The point is not to forget anything, because the ship's store will not have your brand and the next port might be a month away.",
        "groups": [
            {"heading": "Toiletries", "items": [
                {"name": "Shampoo", "asin": "B07N7MWX72",
                 "alex": "", "why": "Bring enough for the whole deployment or accept whatever the ship's store carries by month three. Travel bottles refilled from a big one save locker space."},
                {"name": "Conditioner", "asin": "B0BMJGYVRW",
                 "alex": "", "why": "Ship water, salt air and short showers are hard on hair. Conditioner is the item people skip and then regret."},
                {"name": "Body Wash", "asin": "B06XN6CZ4P",
                 "alex": "", "why": "Bar soap in a shared shower is a losing proposition. A body wash with tea tree or antifungal properties helps with the skin problems that come from communal heads."},
                {"name": "Deodorant", "asin": "B0BS75R47F",
                 "alex": "", "why": "Berthing air, engine rooms and flight decks. Bring more sticks than you think you need; your shipmates will thank you."},
                {"name": "Face Wash", "asin": "B07RL88DD2",
                 "alex": "", "why": "Grease, sweat and recycled air will do a number on your skin. A gentle cleanser at night keeps deployment breakouts under control."},
                {"name": "Foot Cream", "asin": "B0002QB9NE",
                 "alex": "", "why": "Fourteen hours a day in boots leaves feet cracked and sore. A heavy foot cream at night is cheap maintenance on the one body part you cannot work without."},
                {"name": "Cologne or Perfume", "asin": "B00BAZAS7Y",
                 "alex": "", "why": "For port calls and for feeling like a person again after a long stretch underway. A small bottle is plenty."},
                {"name": "Hydrating Face Lotion", "asin": "B00365DABC",
                 "alex": "", "why": "Ship air is dry and the sun topside is relentless. A daily lotion with SPF covers both."},
                {"name": "Toothbrush Container", "asin": "B07CVMV558",
                 "alex": "", "why": "Your toothbrush travels to and from a shared head every day. A ventilated case keeps it off surfaces you do not want to think about."},
                {"name": "Toothpaste", "asin": "B082F1QH7S",
                 "alex": "", "why": "Buy a multipack before you leave. It is the item everyone runs out of at the same time, and the ship's store knows it."},
                {"name": "Mouthwash", "asin": "B00IRKRK9O",
                 "alex": "", "why": "Coffee, watch schedules and not always making it to the head before quarters. A travel bottle in your rack covers the mornings that get away from you."},
                {"name": "Shaving Cream", "asin": "B009WQH8SA",
                 "alex": "", "why": "Grooming standards do not relax underway. A concentrated cream lasts longer than foam and takes up a fraction of the space."},
                {"name": "Dental Floss", "asin": "B08QWYC3MG",
                 "alex": "", "why": "The dentist is on the pier, not on the ship. Floss is the cheapest way to avoid a problem that cannot be fixed until the next port."},
                {"name": "Whitening Strips", "asin": "B00AHAWWO0",
                 "alex": "", "why": "Seven months of galley coffee and energy drinks show. Strips are an easy fix before homecoming photos."},
                {"name": "Boot and Foot Powder", "asin": "B08W5GNXBG",
                 "alex": "", "why": "Sweaty boots on a hot ship are how athlete's foot starts. Powder in the boots every morning keeps them dry and keeps you out of medical."},
                {"name": "Hair Gel and Oil", "asin": "B07YNYD43T",
                 "alex": "", "why": "Whatever your routine is at home, the ship will not have the products for it. Bring your own so you can keep it up."},
                {"name": "Razor", "asin": "B07CZCQ481",
                 "alex": "Make sure to buy extra blades!",
                 "why": "Blades dull fast in ship water and the store's selection is grim. A full deployment of cartridges takes up almost no space."},
                {"name": "Toothbrush", "asin": "B08QWYMMYL",
                 "alex": "Make sure to have more than one in case you drop one on that scary bathroom floor.",
                 "why": "A multipack means you replace it every couple of months like you are supposed to, and you have a spare the day one hits the deck of the head."},
            ]},
            {"heading": "Grooming", "items": [
                {"name": "Loofah", "asin": "B01F88BMC8",
                 "alex": "", "why": "Body wash needs something to go on. Buy a pack, because a loofah in a humid head needs replacing more often than you would at home."},
                {"name": "Nail Clippers", "asin": "B07M5RNH4Z",
                 "alex": "", "why": "Grooming inspections do not stop at sea. A decent set that clips clean beats borrowing the shop's pair."},
                {"name": "Tweezers", "asin": "B0000532A2",
                 "alex": "", "why": "Splinters, wire strands and stray hairs. A precision pair earns its spot in the kit."},
                {"name": "Nail File and Buffer", "asin": "B0017KCQ2W",
                 "alex": "", "why": "Nails break on hatches and dogging wrenches. A file keeps a broken nail from turning into a torn one."},
                {"name": "Reusable Cotton Swab", "asin": "B087Q4TJVC",
                 "alex": "", "why": "One swab that washes clean replaces a box you would run out of. Less to pack and less to throw away in a space where trash is a real problem."},
                {"name": "Cotton Balls", "asin": "B09497R2CN",
                 "alex": "", "why": "Cheap, light and useful for everything from skincare to cleaning a small cut. Keep a bag in the toiletry kit."},
                {"name": "Comb", "asin": "B001VGA4P8",
                 "alex": "", "why": "A comb fits in a coverall pocket for a quick fix before quarters or an inspection. Get one that detangles without pulling."},
                {"name": "Feminine Hygiene Products", "asin": "B08QL1B9XL",
                 "alex": "", "why": "The ship's store stocks a limited selection and runs out. Bring a full deployment's supply of what you actually use, in the most compact form you can find."},
                {"name": "Hair Ties, Clips and Pins", "asin": "B00IGJ1XOO",
                 "alex": "", "why": "Regulation hair takes a lot of elastics and pins, and they vanish underway. A big pack costs nothing and saves the morning scramble."},
                {"name": "Dryer Sheets", "asin": "B0C8X7M477",
                 "alex": "", "why": "Ship laundry comes back stiff and smelling like the ship. A dryer sheet in the load, or tucked in your locker, makes your clothes smell like home."},
                {"name": "Hair Cap", "asin": "B098382QT8",
                 "alex": "", "why": "A satin bonnet protects your hair overnight on a rough pillowcase and keeps it managed between wash days when the showers are short."},
            ]},
            {"heading": "Shower and Laundry", "items": [
                {"name": "Shower Shoes", "asin": "B091ZF4YGX",
                 "alex": "The ship “head” is a public bathroom. To avoid a foot infection you need a barrier between your foot and floor.",
                 "why": "This is not optional. Every corpsman on the ship will tell you the same thing, and a pair of slides is the cheapest medical prevention on this list."},
                {"name": "Toiletry Bag", "asin": "B0815BBB5B",
                 "alex": "Having a carrying case for your toiletries makes life much easier transiting to and from the bathroom. Make sure you can hang it!",
                 "why": "There is no counter space in a ship's head. A bag with a hook hangs off the stall or a pipe and keeps your stuff off the deck."},
                {"name": "Two Towels", "asin": "B07ZS26VNC",
                 "alex": "Two towels is preferred because you can use one for the shower and the other for port calls when you hit the beach or pool. Also if it is laundry day or you drop your towel on the “head” (bathroom) floor having a spare is a life saver.",
                 "why": "Quick-dry towels are worth the money on a ship, because a cotton towel that never dries turns into a mildew problem in your locker."},
                {"name": "Body Wipes", "asin": "B0C22SZQ3Y",
                 "alex": "THROW AWAY! DO NOT FLUSH! Sometimes you will be working outside all day and you don’t have time to shower so body wipes will help you stay fresh.",
                 "why": "Water hours, secured showers and eighteen-hour days happen. Wipes are the shower you take when there is no shower to take."},
                {"name": "Laundry Pods", "asin": "B0BJMNHLXZ",
                 "alex": "Pods vs liquid is more compact, portable and easy to carry when transiting to laundry.",
                 "why": "A jug of liquid detergent is a spill waiting to happen in a moving locker. Pods in a zip bag take up a fraction of the space and carry to the laundry in one hand."},
                {"name": "Laundry Backpack", "asin": "B08R7FP1HT",
                 "alex": "This will make carrying laundry to and from your rack much easier!",
                 "why": "Laundry is several ladders and passageways away, and you need both hands on a ship. A drawstring laundry backpack solves that and doubles as storage."},
                {"name": "Tide To Go Stick", "asin": "B0CGL1CNZK",
                 "alex": "Spilled something on your favorite shirt? Use one of these bad boys.",
                 "why": "Laundry day is a week away and your uniform has to pass inspection tomorrow. The stain pen buys you the time."},
                {"name": "“Battle Roll” (Toilet Paper)", "asin": "B0BB3JGBH5",
                 "alex": "If berthing cleaners forgets to restock the toilet paper or the only available stall doesn’t have any......you can thank me later. Remember to only use single ply so the VCHT (ships plumbing) does not go down.",
                 "why": "Every experienced sailor keeps a personal roll in their rack. The single-ply rule is not a joke; a clogged vacuum system takes down heads for the whole compartment."},
                {"name": "Air Freshener or Odor Absorber", "asin": "B01CESLQ0S",
                 "alex": "These are great to put in your rack so things don’t start to smell.",
                 "why": "Boots, laundry and a closed curtain add up fast. An odor absorber in the locker and a small freshener in the rack keep your six feet of space livable."},
            ]},
        ],
    },
    {
        "slug": "quick-fixes",
        "label": "Quick Fixes",
        "title": "Over-the-Counter Medicine to Pack for Deployment",
        "meta_title": "Over-the-Counter Medicine to Pack for Deployment | Packing List",
        "description": "Sea sickness meds, pain relievers, sleep aids, sunscreen and the other over-the-counter basics to bring on a Navy deployment. Chapter 7 of the packing list.",
        "intro": "General over-the-counter medicine is very handy to have in case medical has a long line, or you need something at an odd hour and don't want to deal with waking people up at night. Keep it in its original packaging, follow the label, and check your command's policy on what you can bring aboard.",
        "items": [
            {"name": "Contact Solution", "asin": "B001GI94SO",
             "alex": "", "why": "The ship's store does not reliably carry it and the brand changes every port. Bring a full deployment's worth, plus a spare pair of glasses for the days your eyes have had enough."},
            {"name": "Excedrin or Advil", "asin": "B012SA8IOO",
             "alex": "", "why": "Headaches from dehydration, noise and no sleep are a daily fact underway. Having your own means you do not stand in the medical line for two tablets."},
            {"name": "Vitamins", "asin": "B00YMSLT88",
             "alex": "", "why": "Fresh produce runs out weeks into deployment. A daily multivitamin covers the gaps in a galley diet."},
            {"name": "Cough Drops", "asin": "B08JHY2W5K",
             "alex": "", "why": "One person gets sick in berthing and the whole compartment follows. Cough drops let you stand your watch without coughing through it."},
            {"name": "Dramamine (Sea Sickness Meds)", "asin": "B007BF7BUY",
             "alex": "", "why": "Even sailors with years at sea get hit in heavy weather. The less-drowsy formula lets you take it and still function on watch."},
            {"name": "Chapstick", "asin": "B01MRH7MR4",
             "alex": "", "why": "Wind, sun and dry ship air crack lips within days. Buy a multipack because you will lose them in every pocket you own."},
            {"name": "Icy Hot", "asin": "B004GEXK2G",
             "alex": "", "why": "Ladders, hatches and working parties are hard on backs and shoulders. A no-mess applicator means you can use it in your rack without getting it everywhere."},
            {"name": "Caffeine Pills", "asin": "B01DFQSVK6",
             "alex": "", "why": "A mid-watch at 0200 after a full workday is the reality of a port and starboard rotation. Pills take up less space than energy drinks and do not need a fridge."},
            {"name": "ZzzQuil", "asin": "B08Y74HSSH",
             "alex": "", "why": "Rotating watch schedules wreck your sleep. Something to help you fall asleep at 1400 when your body thinks it is noon can save a rotation."},
            {"name": "Odor-Eater Insoles", "asin": "B00COYDLOM",
             "alex": "", "why": "Fourteen hours in boots every day, and the boots live in a closed locker. Insoles keep the smell down and add some cushion on steel decks."},
            {"name": "Sunscreen", "asin": "B005IHT94S",
             "alex": "", "why": "Reflection off the water doubles the exposure, and you will be topside for hours during sea and anchor detail or flight ops. Sunburn is also a counseling chit waiting to happen."},
            {"name": "Aloe", "asin": "B08XVR37TP",
             "alex": "", "why": "For the sunburn you got anyway. It also helps with the dry, irritated skin that comes from weeks of recycled air."},
            {"name": "Vapor Rub", "asin": "B000GCHOEM",
             "alex": "", "why": "The berthing cold that goes around every deployment. A little under the nose also helps in spaces that smell like the ship."},
            {"name": "Basic First Aid Kit", "asin": "B0B41MYSGP",
             "alex": "", "why": "Cuts and scrapes from knife edges, ladders and nonskid happen daily. A small kit in your rack handles the minor ones without a trip to medical."},
            {"name": "Pepto-Bismol", "asin": "B000RVLU2Y",
             "alex": "", "why": "Galley food, port call food and stress. Chewable tablets take no space and you will be glad you have them."},
            {"name": "Tums", "asin": "B000UWJPQS",
             "alex": "", "why": "Coffee all day and mid-rats at midnight. Heartburn is standard issue underway, and Tums is the fix."},
            {"name": "Benadryl", "asin": "B0B13PZF8Z",
             "alex": "", "why": "Allergic reactions to something in the galley or a bug bite in port. It is also what a lot of sailors use to reset their sleep after a rotation change."},
            {"name": "Melatonin", "asin": "B08451719W",
             "alex": "", "why": "A gentler option for the same problem: your body clock does not care what section you are in. Fast-dissolve tablets need no water in the rack."},
        ],
    },
    {
        "slug": "miscellaneous",
        "label": "Miscellaneous",
        "title": "Miscellaneous Deployment Essentials Every Sailor Forgets",
        "meta_title": "Miscellaneous Deployment Essentials Sailors Forget | Packing List",
        "description": "Bungee cords, a red headlamp, a multitool, zip ties, a sewing kit and the other small items experienced sailors never deploy without. Chapter 8 of the packing list.",
        "intro": "This is the chapter of things nobody tells you about until you need them. Most of them cost a few dollars, fit in a pocket, and will make you look like you have done this before.",
        "items": [
            {"name": "Religious Text", "asin": "B09X4FGN4X",
             "alex": "No matter what you believe nurturing your spirit will do wonders for your mental health!",
             "why": "Deployment is long and there are hard days. Whatever you read for perspective, bring a copy you can keep in your rack."},
            {"name": "Foot Locker Storage Bin", "asin": "B00TY4AMZQ",
             "alex": "With limited space for storage on the ship, I always kept one of these in a common work center space tucked away to store personal items/snacks. Make sure to lock it!",
             "why": "Your rack lockers fill up fast. A lockable trunk in the shop, where your chief allows it, is where the snack stockpile and the civilian clothes go."},
            {"name": "Boot Polish Set", "asin": "B001AEZ3QG",
             "alex": "Keep this in the work space to share! Always a good thing to have shiny boots.",
             "why": "Inspections and ceremonies do not stop at sea. A shared kit in the shop means the whole work center shows up looking squared away."},
            {"name": "3M Dual Lock (Heavy-Duty Velcro)", "asin": "B09FYCD982",
             "alex": "This stuff is strong! If you need to hang anything on the bulkhead this item will help.",
             "why": "It holds a phone or tablet to the rack overhead and keeps a speaker or fan from launching off the desk in a seaway. It is the most useful roll of tape you will bring."},
            {"name": "Multitool or Knife", "asin": "B0CHYMPVQL",
             "alex": "NOT FOR MAINTENANCE. Great to have on you. You never think you need it until you do.",
             "why": "Opening boxes, cutting line, tightening a loose screw on your rack light. Check your command's knife policy on blade length before you buy one."},
            {"name": "Hand Warmers", "asin": "B004R1J464",
             "alex": "If you have watch outside in the elements or at night you will be glad you have these.",
             "why": "A four-hour lookout watch in the North Atlantic in January is a different kind of cold. A pair in each pocket makes it bearable."},
            {"name": "Knee Pads", "asin": "B08LTMW81Z",
             "alex": "You want that EP Eval? Go do some topside preservation and these will save your knees from the abrasive nonskid floor.",
             "why": "Needle-gunning, painting and scrubbing decks are all done on your knees on a surface designed to be abrasive. Knee pads are the difference between volunteering again and limping for a week."},
            {"name": "Space-Saving Hangers", "asin": "B0BGLLN2XL",
             "alex": "As stated before, there is limited space so these are great for the stand up locker in berthing to save some space.",
             "why": "The stand-up locker fits about six hangers' worth of uniforms. Slim, cascading hangers double that without touching anything else."},
            {"name": "Flash Cards", "asin": "B0BZMQKR4Z",
             "alex": "Studying made easier for that next rank/qualification or certification.",
             "why": "Deployment is when you knock out your warfare pin and study for the advancement exam. Cards fit in a pocket for a slow watch."},
            {"name": "Bungee Cords", "asin": "B07G95PPPW",
             "alex": "SECURE FOR SEA. These are very handy to tie down personal items or keep things together.",
             "why": "Anything not secured will end up on the deck the first time the ship rolls. A pack of bungees keeps your gear, your bin and your chair where you left them."},
            {"name": "Flashlight or Headlamp with Red Light", "asin": "B07QGRWZNB",
             "alex": "Make sure you have a red light for going topside at night (No white lights allowed). It gets VERY dark at night outside.",
             "why": "Darkened ship means no white light on the weather decks, period. A headlamp with a red mode keeps your hands free on the ladders and keeps you out of trouble with the bridge."},
            {"name": "Pocket Notebook", "asin": "B0878Y5TVR",
             "alex": "Take notes at quarters and carry this around all day to jot things down so you don’t forget.",
             "why": "Every chief expects you to write down what was passed at quarters. A notebook that fits the coverall chest pocket is the one you will actually carry."},
            {"name": "Passport and ID Protector", "asin": "B07H3PHFM8",
             "alex": "Always protect your personal information.",
             "why": "Your CAC, passport and cards go with you on every port call. An RFID-blocking holder keeps them together and keeps them from being skimmed in a crowded market."},
            {"name": "Ziploc Bags", "asin": "B00J2LD2KS",
             "alex": "", "why": "Wet gear, opened snacks, a phone on a rainy port call, small parts from a job. There is no problem on a ship a zip bag does not help with."},
            {"name": "Drawstring Bag (for Port Calls)", "asin": "B07T87YQZL",
             "alex": "", "why": "Water, sunscreen, a charger and a towel for a day on liberty. It packs flat in your locker between ports."},
            {"name": "Zip Ties", "asin": "B08TVLYB3Q",
             "alex": "", "why": "Securing cables, hanging a fan, fixing a broken locker latch until the hull techs get to it. Bring a bag of assorted sizes."},
            {"name": "Gorilla Tape or Duct Tape", "asin": "B07GRJ8L55",
             "alex": "", "why": "It fixes boots, bags, headphones and rack curtains. Wrap a few feet around a pen if you do not want to carry the roll."},
            {"name": "Gorilla Glue", "search": "Gorilla Glue",
             "alex": "", "why": "For the repairs tape cannot do: a boot sole, a broken handle, a cracked phone case. The ship's store will not have it."},
            {"name": "Sewing Kit", "asin": "B00MG5FZWA",
             "alex": "", "why": "A popped button or a torn seam on your uniform the night before inspection. The ship has no tailor, so you are the tailor."},
            {"name": "Small Backpack", "asin": "B08J7T921K",
             "alex": "", "why": "For overnight liberty, extra storage and day use. A daypack that folds small carries your gear on the pier and your essentials on a port call."},
        ],
    },
]
